version: 2
jobs:
  build:
    docker:
      - image: robrotheram/gogoallery_ci:1.15
    steps:
      - checkout
      - setup_remote_docker

      # specify any bash command here prefixed with `run: `
      - run: make dep
      - run: make build-dashboard 
      - run: make build-server
      - run: make package
      - store_artifacts:
          path: gogallery-linux-amd64.tgz
          destination: gogallery-linux-amd64.tgz

      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: make docker
      - run: make docker-publish
