version: 2
jobs:
  build:
    docker:
      - image: robrotheram/gogoallery_ci:1.13
    steps:
      - checkout
      - setup_remote_docker

      # specify any bash command here prefixed with `run: `
      - run: make build-dashboard 
      - run: make build-ui 
      - run: make build-server
      - run: make package
      - store_artifacts:
          path: gogallery-linux-amd64.tgz
          destination: gogallery-linux-amd64.tgz