name: Makefile CI

on:
  push:
    branches: [ "master", "v4" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
          
    - name: Install dependencies
      run: make build
